"""add smtp settings to event

Revision ID: 015
Revises: 014
Create Date: 2026-06-14 17:59:04.756842

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '015'
down_revision: Union[str, Sequence[str], None] = '014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('smtp_host', sa.String(length=200), nullable=True))
    op.add_column('events', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('smtp_username', sa.String(length=200), nullable=True))
    op.add_column('events', sa.Column('smtp_password', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('smtp_sender_email', sa.String(length=320), nullable=True))
    op.add_column('events', sa.Column('smtp_sender_name', sa.String(length=200), nullable=True))
    op.add_column('events', sa.Column('smtp_use_tls', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'smtp_use_tls')
    op.drop_column('events', 'smtp_sender_name')
    op.drop_column('events', 'smtp_sender_email')
    op.drop_column('events', 'smtp_password')
    op.drop_column('events', 'smtp_username')
    op.drop_column('events', 'smtp_port')
    op.drop_column('events', 'smtp_host')
    # ### end Alembic commands ###
